spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:books-library;INIT=CREATE SCHEMA IF NOT EXISTS bookslibrary
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect